# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/ntest12',
                'doc_host': 'https://hamelsmu.github.io',
                'git_url': 'https://github.com/hamelsmu/ntest12',
                'lib_path': 'ntest12'},
  'syms': {'ntest12.core': {'ntest12.core.foo': ('core.html#foo', 'ntest12/core.py')}}}